from PyQt6.QtWidgets import *
app = QApplication([])
window = QWidget()
window.resize(200,300)
layout = QVBoxLayout()
layout.addWidget(QPushButton('Top'))
layout.addWidget(QPushButton('Bottom'))
window.setLayout(layout)
window.show()
app.exec()